export const phrases = [
  `Hi, who just joined?`,
  `Can you email that to everyone?`,
  `____, are you there?`,
  `Uh, ____, you're still sharing.`,
  `Hey guys, I have to jump to another call.`,
  `<em>(Sound of someone typing, possibly with a hammer)</em>`,
  `<em>(Loud, painful echo/feedback)</em>`,
  `<em>(Child or animal noises)</em>`,
  `Hi, can you hear me?`,
  `No, it's still loading.`,
  `Next slide, please.`,
  `Can everyone go on mute?`,
  `I'm sorry, I was on mute.`,
  `Sorry, go ahead.`,
  `Hello? Hello?`,
  `<span>Sorry I'm late. <em>(Insert lame excuse)</em></span>`,
  `I have a hard stop at...`,
  `I'm sorry, you cut out there.`,
  `Can we take this offline?`,
  `I'll have to get back to you.`,
  `Can everyone see my screen?`,
  `Sorry, I was having connection issues.`,
  `I think there's a lag.`,
  `Sorry, didn't catch that. Can you repeat?`,
  `<span>So <em>(faded out)</em> I can <em>(inaudible)</em> by <em>(garbled)</em>, OK?</span>`
];
