export const phrases = [
  `Hi, who just joined?`,
  `Can you email that to everyone?`,
  `____, are you there?`,
  `Uh, ____, you're still sharing.`,
  `Hey guys, I have to jump to another call.`,
  `(Sound of someone typing, possibly with a hammer)`,
  `(Loud, painful echo/feedback)`,
  `(Child or animal noises)`,
  `Hi, can you hear me?`,
  `No, it's still loading.`,
  `Next slide, please.`,
  `Can everyone go on mute?`,
  `I'm sorry, I was on mute.`,
  `Sorry, go ahead.`,
  `Hello? Hello?`,
  `Sorry I'm late. (Insert lame excuse)`,
  `I have a hard stop at...`,
  `I'm sorry, you cut out there.`,
  `Can we take this offline?`,
  `I'll have to get back to you.`,
  `Can everyone see my screen?`,
  `Sorry, I was having connection issues.`,
  `I think there's a lag.`,
  `Sorry, didn't catch that. Can you repeat?`,
  `So <faded out> I can <inaudible> by <garbled>, OK?`
];
